# Generated by Django 2.2.6 on 2020-12-30 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student1',
            fields=[
                ('stuid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('roll', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='stu_subject',
            fields=[
                ('marks', models.IntegerField(primary_key=True, serialize=False)),
                ('maths', models.CharField(max_length=50)),
                ('english', models.CharField(max_length=50)),
                ('chemistry', models.CharField(max_length=50)),
                ('physics', models.CharField(max_length=50)),
                ('stuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='ApiApp.Student')),
            ],
        ),
    ]
