# Generated by Django 2.2.6 on 2020-12-30 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApp', '0002_stu_subject_student1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stu_subject',
            name='stuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='ApiApp.student1'),
        ),
    ]
